### ISSUE TITLE
error from '-profile test'

### ISSUE THREAD

**Issue by sundysun99** [nf-core/mhcquant#309] opened 2024-02-23 09:07 UTC
### Description of the bug

Hi,

I got an error in the first step, 'profile test'. Here is the relevant report. Maybe there is something wrong with my singularity.

### Command used and terminal output

```console
$ nextflow run nf-core/mhcquant -r 2.5.0 -profile test,singularity --outdir ./result_test

N E X T F L O W  ~  version 23.10.1
Launching `https://github.com/nf-core/mhcquant` [distracted_cori] DSL2 - revision: b80a5a4fbf [2.5.0]


------------------------------------------------------
                                        ,--./,-.
        ___     __   __   __   ___     /,-._.--~'
  |\ | |__  __ /  ` /  \ |__) |__         }  {
  | \| |       \__, \__/ |  \ |___     \`-._,-`-,
                                        `._,._,'
  nf-core/mhcquant v2.5.0-gb80a5a4
------------------------------------------------------
Core Nextflow options
  revision                        : 2.5.0
  runName                         : distracted_cori
  containerEngine                 : singularity
  launchDir                       : /dssg/home/acct-lulu0113/lulu0113-sd/IMpeptide/MHCquant
  workDir                         : /dssg/home/acct-lulu0113/lulu0113-sd/IMpeptide/MHCquant/work
  projectDir                      : /dssg/home/acct-lulu0113/lulu0113-sd/.nextflow/assets/nf-core/mhcquant
  userName                        : lulu0113-sd
  profile                         : test,singularity
  configFiles                     : 

Input/output options
  input                           : https://raw.githubusercontent.com/nf-core/test-datasets/mhcquant/testdata/HepG2_sample_sheet.tsv
  outdir                          : ./result_test

Database Options
  fasta                           : https://raw.githubusercontent.com/nf-core/test-datasets/mhcquant/testdata/UP000005640_9606.fasta

Mass Spectrometry Data Processing
  fragment_mass_tolerance         : 0.01
  fixed_mods                      :  
  default_params_file_comet       :  

Rescoring
  description_correct_features    : 0
  subset_max_train                : 0
  deeplc_calibration_bins         : 20
  deeplc_calibration_mode         : idx_bin
  ms2pip_model_name               : Immuno-HCD

Quantification Options
  skip_quantification             : true
  quantification_min_prob         : 0
  quantification_mz_window        : 5
  quantification_rt_window        : 0
  quantification_mapping_tolerance: 0
  quantification_peak_width       : 60
  quantification_min_peak_width   : 0.2

Institutional config options
  config_profile_name             : Test profile
  config_profile_description      : Minimal test dataset to check pipeline function

Max job request options
  max_cpus                        : 2
  max_memory                      : 6.GB
  max_time                        : 6.h

!! Only displaying parameters that differ from the pipeline defaults !!
------------------------------------------------------
If you use nf-core/mhcquant for your analysis please cite:

* The pipeline publication
  https://doi.org/10.1021/acs.jproteome.9b00313

* The pipeline
  https://doi.org/10.5281/zenodo.1569909

* The nf-core framework
  https://doi.org/10.1038/s41587-020-0439-x

* Software dependencies
  https://github.com/nf-core/mhcquant/blob/master/CITATIONS.md

executor >  local (6)
[5a/04d86f] process > NFCORE_MHCQUANT:MHCQUANT:INPUT_CHECK:SAMPLESHEET_CHECK (HepG2_sample_sheet.tsv) [100%] 1 of 1 ✔
[90/0ea659] process > NFCORE_MHCQUANT:MHCQUANT:OPENMS_DECOYDATABASE (3)                               [100%] 3 of 3 ✔
[-        ] process > NFCORE_MHCQUANT:MHCQUANT:THERMORAWFILEPARSER                                    -
[-        ] process > NFCORE_MHCQUANT:MHCQUANT:TDF2MZML                                               -
[6f/a32452] process > NFCORE_MHCQUANT:MHCQUANT:OPENMS_COMETADAPTER (2)                                [  0%] 0 of 2
executor >  local (6)
[5a/04d86f] process > NFCORE_MHCQUANT:MHCQUANT:INPUT_CHECK:SAMPLESHEET_CHECK (HepG2_sample_sheet.tsv) [100%] 1 of 1 ✔
[90/0ea659] process > NFCORE_MHCQUANT:MHCQUANT:OPENMS_DECOYDATABASE (3)                               [100%] 3 of 3 ✔
[-        ] process > NFCORE_MHCQUANT:MHCQUANT:THERMORAWFILEPARSER                                    -
[-        ] process > NFCORE_MHCQUANT:MHCQUANT:TDF2MZML                                               -
[6f/a32452] process > NFCORE_MHCQUANT:MHCQUANT:OPENMS_COMETADAPTER (2)                                [ 50%] 1 of 2, failed: 1
executor >  local (6)
[5a/04d86f] process > NFCORE_MHCQUANT:MHCQUANT:INPUT_CHECK:SAMPLESHEET_CHECK (HepG2_sample_sheet.tsv) [100%] 1 of 1 ✔
[90/0ea659] process > NFCORE_MHCQUANT:MHCQUANT:OPENMS_DECOYDATABASE (3)                               [100%] 3 of 3 ✔
[-        ] process > NFCORE_MHCQUANT:MHCQUANT:THERMORAWFILEPARSER                                    -
[-        ] process > NFCORE_MHCQUANT:MHCQUANT:TDF2MZML                                               -
[6f/a32452] process > NFCORE_MHCQUANT:MHCQUANT:OPENMS_COMETADAPTER (2)                                [ 33%] 1 of 3, failed: 1
executor >  local (6)
[5a/04d86f] process > NFCORE_MHCQUANT:MHCQUANT:INPUT_CHECK:SAMPLESHEET_CHECK (HepG2_sample_sheet.tsv) [100%] 1 of 1 ✔
[90/0ea659] process > NFCORE_MHCQUANT:MHCQUANT:OPENMS_DECOYDATABASE (3)                               [100%] 3 of 3 ✔
[-        ] process > NFCORE_MHCQUANT:MHCQUANT:THERMORAWFILEPARSER                                    -
[-        ] process > NFCORE_MHCQUANT:MHCQUANT:TDF2MZML                                               -
[61/5f3ea1] process > NFCORE_MHCQUANT:MHCQUANT:OPENMS_COMETADAPTER (3)                                [ 66%] 2 of 3, failed: 2
executor >  local (6)
[5a/04d86f] process > NFCORE_MHCQUANT:MHCQUANT:INPUT_CHECK:SAMPLESHEET_CHECK (HepG2_sample_sheet.tsv) [100%] 1 of 1 ✔
[90/0ea659] process > NFCORE_MHCQUANT:MHCQUANT:OPENMS_DECOYDATABASE (3)                               [100%] 3 of 3 ✔
[-        ] process > NFCORE_MHCQUANT:MHCQUANT:THERMORAWFILEPARSER                                    -
[-        ] process > NFCORE_MHCQUANT:MHCQUANT:TDF2MZML                                               -
[61/5f3ea1] process > NFCORE_MHCQUANT:MHCQUANT:OPENMS_COMETADAPTER (3)                                [ 66%] 2 of 3, failed: 2
executor >  local (6)
[5a/04d86f] process > NFCORE_MHCQUANT:MHCQUANT:INPUT_CHECK:SAMPLESHEET_CHECK (HepG2_sample_sheet.tsv) [100%] 1 of 1 ✔
[90/0ea659] process > NFCORE_MHCQUANT:MHCQUANT:OPENMS_DECOYDATABASE (3)                               [100%] 3 of 3 ✔
[-        ] process > NFCORE_MHCQUANT:MHCQUANT:THERMORAWFILEPARSER                                    -
[-        ] process > NFCORE_MHCQUANT:MHCQUANT:TDF2MZML                                               -
[61/5f3ea1] process > NFCORE_MHCQUANT:MHCQUANT:OPENMS_COMETADAPTER (3)                                [ 66%] 2 of 3, failed: 2[-        ] process > NFCORE_MHCQUANT:MHCQUANT:OPENMS_PEPTIDEINDEXER                                  -
[-        ] process > NFCORE_MHCQUANT:MHCQUANT:OPENMS_IDMERGER                                        -
[-        ] process > NFCORE_MHCQUANT:MHCQUANT:OPENMS_PSMFEATUREEXTRACTOR                             -
[-        ] process > NFCORE_MHCQUANT:MHCQUANT:OPENMS_PERCOLATORADAPTER                               -
[-        ] process > NFCORE_MHCQUANT:MHCQUANT:OPENMS_IDFILTER_Q_VALUE                                -
[-        ] process > NFCORE_MHCQUANT:MHCQUANT:OPENMS_TEXTEXPORTER                                    -[-        ] process > NFCORE_MHCQUANT:MHCQUANT:OPENMS_MZTABEXPORTER                                   -
[-        ] process > NFCORE_MHCQUANT:MHCQUANT:CUSTOM_DUMPSOFTWAREVERSIONS                            -
[-        ] process > NFCORE_MHCQUANT:MHCQUANT:MULTIQC                                                -
-[nf-core/mhcquant] Pipeline completed with errors-
ERROR ~ Error executing process > 'NFCORE_MHCQUANT:MHCQUANT:OPENMS_COMETADAPTER (2)'
Caused by:
  Process `NFCORE_MHCQUANT:MHCQUANT:OPENMS_COMETADAPTER (2)` terminated with an error exit status (3)

Command executed:

  CometAdapter -in HepG2_rep2_small.mzML \      -out HepG2_rep2_small.idXML \
      -database UP000005640_9606_decoy.fasta \      -threads 2 \      -pin_out HepG2_rep2_small_pin.tsv \
       \
      -precursor_mass_tolerance 5 -fragment_mass_tolerance 0.01 -fragment_bin_offset 0.0 -instrument high_res -num_hits 1 -digest_mass_range 800:2500 -max_variable_mods_in_peptide 3 -missed_cleavages 0 -precursor_charge 2:3 -activation_method ALL -variable_modifications 'Oxidation (M)' -enzyme 'unspecific cleavage' -spectrum_batch_size 0 \
      -fixed_modifications \
       \       \
       \       \
       \
      cat <<-END_VERSIONS > versions.yml
  "NFCORE_MHCQUANT:MHCQUANT:OPENMS_COMETADAPTER":      openms-thirdparty: $(echo $(FileInfo --help 2>&1) | sed 's/^.*Version: //; s/-.*$//' | sed 's/ -*//; s/ .*$//')
  END_VERSIONS
Command exit status:  3
Command output:
  The mzML file provided to CometAdapter is not indexed, but comet requires one. We will add an index by writing a temporary file. If you run this analysis more often, consider indexing your mzML in advance!
Command error:  INFO:    Environment variable SINGULARITYENV_TMPDIR is set, but APPTAINERENV_TMPDIR is preferred  INFO:    Environment variable SINGULARITYENV_NXF_TASK_WORKDIR is set, but APPTAINERENV_NXF_TASK_WORKDIR is preferred  INFO:    Environment variable SINGULARITYENV_NXF_DEBUG is set, but APPTAINERENV_NXF_DEBUG is preferred
  IndexedMzMLDecoder::findIndexListOffset Error: Could not find element indexListOffset in the last 1023 bytes. Maybe this is not a indexedMzML.The mzML file provided to CometAdapter is not indexed, but comet requires one. We will add an index by writing a temporary file. If you run this analysis more often, consider indexing your mzML in advance!  IAH1HtAAAAAQH7Ue0AAAACggdx7QAAAAKCX3ntAAAAAwOrhe0AAAABgGul7QAAAAIDp63tAAAAAIJbxe0AAAAAg3fF7QAAAAGBo83tAAAAAoO7ze0AAAAAgjPV7QAAAAGAJ+XtAAAAAAMz7e0AAAABgZf57QAAAAEDcAXxAAAAAwLkDfEAAAADgmAV8QAAAACAkEXxAAAAAgNIRfEAAAAAAmRN8QAAAAMCeG3xAAAAA4MAefEAAAADAPzN8QAAAAOCjM3xAAAAAoEA0fEAAAAAAVER8QAAAAKAWS3xAAAAA4GZLfEAAAAAgzkt8QAAAAED2S3xAAAAAAO1NfEAAAABgY058QAAAAGDLU3xAAAAAoP1TfEAAAABgNVR8QAAAAMCBVHxAAAAA4MBYfEAAAADgFlx8QAAAACAZXnxAAAAAYNdjfEAAAABADGR8QAAAAEDMaHxAAAAA4GtufEAAAADgBn58QAAAAEAchHxAAAAAIMqRfEAAAABg/JN8QAAAACBqlHxAAAAA4ImUfEAAAADgOZV8QAAAAMDgmXxAAAAAAHycfEAAAADA8Z18QAAAAMD1o3xAAAAAYIKkfEAAAAAg8Kt8QAAAAKDBsnxAAAAAQLOzfEAAAADgMLR8QAAAAGA3vHxAAAAAIFi8fEAAAAAAA8V8QAAAAADnzXxAAAAAYLTSfEAAAADAbNN8QAAAAOBY4nxAAAAAIDTjfEAAAAAgEOx8QAAAAKB67HxAAAAAQBjyfEAAAADAVPJ8QAAAAACp83xAAAAAAET0fEAAAABggvR8QAAAACAC+XxAAAAAIBD9fEAAAADgYf58QAAAAAAwAX1AAAAAgEgCfUAAAACgLgR9QAAAAAAXBX1AAAAAIAUJfUAAAAAg1gt9QAAAAOB+DH1AAAAA4EMNfUAAAABgRRJ9QAAAAMARFH1AAAAAwDYUfUAAAAAAjhh9QAAAACCJHH1AAAAAYBUkfUAAAAAAGyx9QAAAACA5LX1AAAAAgKExfUAAAADAKTR9QAAA
  /opt/conda/conda-bld/openms-meta_1691398820198/work/src/openms/source/FORMAT/HANDLERS/XMLHandler.cpp(130): While loading 'HepG2_rep2_small.mzML': input ended before all started tags were ended; last tag started is 'binary'( in line 76018 column 21927)
  Error: Unable to read file (- due to that error of type Parse Error in: /opt/conda/conda-bld/openms-meta_1691398820198/work/src/openms/source/FORMAT/HANDLERS/XMLHandler.cpp@131-void OpenMS::Internal::XMLHandler::fatalError(ActionMode, const OpenMS::String&, OpenMS::UInt, OpenMS::UInt) const)

Work dir:
  /dssg/home/acct-lulu0113/lulu0113-sd/IMpeptide/MHCquant/work/6f/a32452baa4c24bdca43862cef921ae

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

 -- Check '.nextflow.log' file for details
```

### System information

nextflow version 23.10.1
Singularity version: apptainer version 1.2.5-1.el8

**Comment by jonasscheid** [comment] 2024-02-23 09:28
Looks like the test files are corrupt / did not get staged properly. I cannot reproduce your error on a local singularity instance, but since you use apptainer, can you try

`$ nextflow run nf-core/mhcquant -r 2.5.0 -profile test,apptainer --outdir ./result_test`

**Comment by jonasscheid** [comment] 2024-04-01 20:43
@sundysun99 Did you have the time to have a look again?

**Comment by jonasscheid** [comment] 2024-05-12 18:10
Closing this one @sundysun99. If you still have issues, feel free to reopen or join nf-core Slack to get in touch!

**Closed by jonasscheid** 2024-05-12 18:10 UTC
Labels: bug
