### ISSUE TITLE
Issue in the MzTabExporter

### ISSUE THREAD

**Issue by marissaDubbelaar** [nf-core/mhcquant#230] opened 2022-11-14 12:48 UTC
### Description of the bug

I experienced the following issue on the dev branch, and I would like to resolve this before release (of course), but I have no idea where to look for this. I noticed a similar issue request on [OpenMS](https://github.com/OpenMS/OpenMS/issues/5357)
The major difference is that I tried to update OpenNMS from 2.6.0 to 2.8.0 on the dev branch, I will go over the changes between these two versions, but some input would be highly appreciated.

The following error is returned:

```
Caused by:
  Process `NFCORE_MHCQUANT:MHCQUANT:PROCESS_FEATURE:OPENMS_MZTABEXPORTER_QUANT (QAMTL477AO_J314_Pre_T39L243_J314_Pre_T39L243)` terminated with an error exit status (8)

Command executed:

  MzTabExporter -in QAMTL477AO_J314_Pre_T39L243_J314_Pre_T39L243_resolved.consensusXML \
      -out QAMTL477AO_J314_Pre_T39L243_J314_Pre_T39L243.mzTab \
      -threads 2 \
  
  
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_MHCQUANT:MHCQUANT:PROCESS_FEATURE:OPENMS_MZTABEXPORTER_QUANT":
      openms: $(echo $(FileInfo --help 2>&1) | sed 's/^.*Version: //; s/-.*$//' | sed 's/ -*//; s/ .*$//')
  END_VERSIONS

Command exit status:
  8

Command output:
  No fractions annotated in consensusXML. Assuming unfractionated.
  Error: Unexpected internal error (PSM controllerType=0 controllerNumber=1 scan=9440 does not map to an MS file registered in the quantitative metadata. Check your merging and filtering steps and/or report the issue, please.)
  <No fractions annotated in consensusXML. Assuming unfractionated.> occurred 4 times

Command wrapper:
  nxf-scratch-dir node003:/scratch/117012/nxf.8kITDHhTPh
  No fractions annotated in consensusXML. Assuming unfractionated.
  Error: Unexpected internal error (PSM controllerType=0 controllerNumber=1 scan=9440 does not map to an MS file registered in the quantitative metadata. Check your merging and filtering steps and/or report the issue, please.)
  <No fractions annotated in consensusXML. Assuming unfractionated.> occurred 4 times

```

I also looked into the file of interest and I could file a `spectrum_reference` annotated.

```
<consensusElement id="e_11275396928539264273" quality="3.574097" charge="5">
			<centroid rt="2886.454795973814726" mz="527.123682987430925" it="3.764833e06"/>
			<groupedElementList>
				<element map="0" id="28923268865551816" rt="2897.00668984044114" mz="527.123682987430925" it="4.085203e06" charge="5"/>
				<element map="1" id="14924012554702823270" rt="2882.901894744373749" mz="527.123682987430925" it="3.478242e06" charge="5"/>
				<element map="2" id="13437987073385272035" rt="2880.484798142305408" mz="527.123682987430925" it="3.642787e06" charge="5"/>
				<element map="3" id="1164487179193034968" rt="2885.425801168138605" mz="527.123682987430925" it="3.8531e06" charge="5"/>
			</groupedElementList>
			<PeptideIdentification identification_run_ref="PI_0" score_type="q-value" higher_score_better="false" significance_threshold="0" MZ="527.1254486319" RT="2874.61804275669" spectrum_reference="controllerType=0 controllerNumber=1 scan=9440" >
				<PeptideHit score="0.0126048" sequence="ANANSRQQIRKLIKDGLIIRKPV" charge="5" aa_before="I I I I I I I" aa_after="T T T T T T T" start="32 32 32 29 52 52 32" end="54 54 54 51 74 74 54" protein_refs="PH_219 PH_1709 PH_1272 PH_1265 PH_1253 PH_937 PH_927">
					<UserParam type="string" name="target_decoy" value="target"/>
					<UserParam type="string" name="MS:1002258" value="11"/>
					<UserParam type="string" name="MS:1002259" value="176"/>
					<UserParam type="string" name="num_matched_peptides" value="4252"/>
					<UserParam type="int" name="isotope_error" value="0"/>
					<UserParam type="float" name="MS:1002252" value="2.234"/>
					<UserParam type="float" name="MS:1002253" value="1.0"/>
					<UserParam type="float" name="MS:1002254" value="0.0"/>
					<UserParam type="float" name="MS:1002255" value="25.699999999999999"/>
					<UserParam type="float" name="MS:1002256" value="1.0"/>
					<UserParam type="float" name="MS:1002257" value="0.0494"/>
					<UserParam type="string" name="protein_references" value="non-unique"/>
					<UserParam type="float" name="COMET:deltCn" value="1.0"/>
					<UserParam type="float" name="COMET:deltLCn" value="0.0"/>
					<UserParam type="float" name="COMET:lnExpect" value="-3.00780485478826"/>
					<UserParam type="float" name="COMET:lnNumSP" value="8.355144739461839"/>
					<UserParam type="float" name="COMET:lnRankSP" value="0.0"/>
					<UserParam type="float" name="COMET:IonFrac" value="0.0625"/>
					<UserParam type="float" name="MS:1001492" value="0.412529"/>
					<UserParam type="float" name="MS:1001491" value="0.0126048"/>
					<UserParam type="float" name="MS:1001493" value="0.245321"/>
				</PeptideHit>
				<UserParam type="int" name="id_merge_index" value="4"/>
				<UserParam type="string" name="FFId_category" value="internal"/>
				<UserParam type="int" name="map_index" value="0"/>
				<UserParam type="string" name="feature_id" value="11275396928539264273"/>
			</PeptideIdentification>
			<UserParam type="string" name="feature_id" value="11275396928539264273"/>
		</consensusElement>
```

### Command used and terminal output

```console
nextflow run nf-core/mhcquant \
-r dev \
-profile cfc \
--input input.tsv \
--outdir ./results \
--fasta *.fasta \
--digest_mass_range 800:2500 \
--activation_method CID \
--prec_charge 2:3 \
--fdr_threshold 0.05 \
--number_mods 3 \
--precursor_mass_tolerance 5 \
--fragment_mass_tolerance 0.02 \
--num_hits 1 \
--peptide_min_length 8 \
--peptide_max_length 12 \
--max_rt_alignment_shift 300 \
--max_time '240.h' \
--email marissa.dubbelaar@uni-tuebingen.de
```

### Relevant files

[nextflow.log](https://github.com/nf-core/mhcquant/files/10003045/nextflow.log)

### System information

- Nextflow version: 22.04.4
- Hardware: HPC
- Container engine: Singularity
- Version of nf-core/mhcquant: dev

**Comment by timosachsenberg** [comment] 2022-11-14 16:30
This usually indicates that the native ids in the annotated mzML file doesn't match to the native ids in the identification files. 
The quantification looks sane to me @jpfeuffer? any idea:
https://github.com/nf-core/mhcquant/blob/master/subworkflows/local/post_quantification.nf
and it is run on the aligned files:
https://github.com/nf-core/mhcquant/blob/master/workflows/mhcquant.nf#L241-L250

**Comment by jpfeuffer** [comment] 2022-11-14 17:27
The problem is that this PeptideIdentification has an id_merge_index of 4 and a map_index of 0 this means that you are linking or otherwise merging files that were annotated with IDs from multiple files.
In the new version we require a unique path back to the fragment spectrum in the mzml file.
This does not seem to be possible with how the workflow is constructed/parameterized. I won't have the time to look into the workflow before the weekend though I think.

**Comment by jpfeuffer** [comment] 2022-11-14 17:29
It might also be that one of the tools used was not updated yet to pass through information from merged ID files.

**Comment by marissaDubbelaar** [comment] 2022-11-16 14:33
I think that I found the problem, apparently, upstream not all of the individual files were given somehow which resulted in a conflict later on (trying to refer to an ID that was not available).

**Closed** 2022-12-01 15:07 UTC
Labels: bug
